### PR TITLE
Add Fallback to Codepagex (pure Elixir) when iconv (NIF) is unavailable

### PR DESCRIPTION
**Pull request by heri16**

### CODE REVIEW

**Comment by heri16** [comment]
Let me elaborate a little. When the user has a problematic build toolchain, and cannot build NIFs, or is inside a docker container that has no compiler, at least there is some minimal support via Codepagex, instead of MimeMail crashing the mix run, preventing the whole app from starting up. When Codepagex matures further (maintainer currently looking to optimize speed), it would be the main module to use for char set conversion, because NIFs are evil (they slow down the BEAM VM scheduler).

**Comment by heri16** [comment]
We must not be narrow minded. There are many more environments where Elixir run that we might not be aware of. For example, the Nerves Elixir project uses it for embedded chipsets. The cross-compiler for the chipset might be difficult to setup or to obtain officially. Also hardware limitations are everywhere. Compiling anything on the 9-dollar C.H.I.P. computer with is insanity. @awetzel

**Comment by awetzel** [comment]
Actually I think the iconv nif will always be much more efficient than the Elixir version, so in an embedded env, the cross compiled version will be much more efficient but more difficult to compile.

iconv is a rock solid library used by so many project that it is reliable to use it as a Nif. Then the use case in mailibex : *convert ASCII with encoded special chars bodies to utf8 elixir binary* is bounded (to the size of a text content of a mail, often way < 1MB and so <1ms with most modern CPUs, even embeded) http://erlang.org/doc/man/erl_nif.html#lengthy_work 

I actually am a Nerves user (but not with mailibex specifically), and Nerves can be used as a cross compilation helper (along with a cross-compiled package management) which make the build possible. So if the compiler use `CC` `CFLAGS` environment variable or make case with the `CROSSCOMPILE` env (set by nerves) then it should be easily cross compiled with nerves.

Still :) I agree an Elixir implementation would be better since the use of iconv here was not for perf but because there was no alternative in elixir/erlang when I did it. 
Also even if making a nif for encoding conversion (and so make a single erlang reduction for each body decoding) is usable in the "normal" case, it make a DDOS attack really easy for servers open on the internet : you just have to send a mail with a 1GB text body Latin1 encoded in order to break the erlang VM.

So thank you for the PR :)

**Comment by heri16** [comment]
Absolutely agree with the Denial of service part.

**Comment by awetzel** [comment]
I pushed it yesterdya to hex.pm as `0.1.1` version.

**Pull request merged**
